### ISSUE TITLE
MongoDB vs SQLite vs MySQL

### ISSUE THREAD

**Issue by johnsriot** [reggieroby/face_mask#15]
After a chat on Saturday I was wanting to get some group feedback as to what kind of database we would like to use. Given we will be working with Flask on the back end, we have plenty of support to use Mongo, SQLite, or MySQL. We will need to store both user login data as well as the data collected from our survey.

**Comment by reggieroby** [comment]
id go with either mongo or mysql. sqlite is for development use.

**Comment by reggieroby** [comment]
final decisions?

**Comment by johnsriot** [comment]
We should just go with mySQL at this point.
