### ISSUE TITLE
Flask Backend

### ISSUE THREAD

**Issue by johnsriot** [reggieroby/face_mask#16]
I created a branch for both peer review and to get early feedback. Currently, the branch is buggy so I don't intend on merging this branch yet. Feel free to ask questions and share ideas.

**Comment by johnsriot** [comment]
I have updated my code and pushed it to the "backend" branch. Please review as I would like to push this branch soon if everyone is okay with it. As I write more code I get more scope creep, but a few thoughts I have are:

- We need another table to store the data the users submit, I have coded the "dashboard" so that we can retrieve the data after login. (I was just going to call the table "survey" unless someone has a better naming convention)

- Do we want to create an admin panel?

- Need more backend validation.

- Do we want to create a page so users can update/change email and password?

- Do we want to breakdown the routes into smaller pieces?

**Comment by reggieroby** [comment]
does it work?

**Comment by reggieroby** [comment]
to me these questions are all issues to track. this issue is just getting a foundation in place.

**Comment by johnsriot** [comment]
Login endpoints work correctly. /Dashboard will be a future feature.
