### ISSUE TITLE
Create survey model

### ISSUE THREAD

**Issue by GT-rc** [reggieroby/face_mask#23]
We need a model for the survey data

**Comment by johnsriot** [comment]
class Survey(db.model):
    """ Survey data collected from user """
    id = db.Column(db.Integer, primary_key=True)
    dryness = db.Column(db.Integer)
    oiliness = db.Column(db.Integer)
    redness = db.Column(db.Integer)
    sensitivity = db.Column(db.Integer)
    acne = db.Column(db.Integer)
    wrinkles = db.Column(db.Boolean, default=False)
    scarring = db.Column(db.Boolean, default=False)
    user_id = db.Column(db.Integer, db.ForeignKey('user.id'), nullable=False)

This is that model I was talking about, use it, trash it, or whatever.
